#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
#
# Push the AUR package for a released version.
#
#   scripts/publish_aur.sh <version>      # e.g. 0.0.32
#
# Why this is a script and not a goreleaser pipe
#
# goreleaser can push to the AUR, but only from inside the release job —
# where a failure would abort the release and cost it its artefacts,
# signatures and attestations. aur.archlinux.org being unreachable for an
# hour is not a reason to lose a release's provenance. So the pipe runs
# with skip_upload and this runs afterwards, in a job that cannot fail the
# release.
#
# The PKGBUILD is written here, from the checksums of the tarballs this
# script downloads from the signed release — so it cannot disagree with what
# was published. (An earlier version of this comment claimed the file was
# generated by goreleaser and merely fetched. It never was; the heredoc
# below has always written it.)
set -euo pipefail

version="${1:?usage: publish_aur.sh <version>}"
repo="${CORRAL_REPO:-sebastienrousseau/corralctl}"
pkg="corralctl-bin"
workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

cd "$(git rev-parse --show-toplevel)"

# The checksums the PKGBUILD must carry are the ones in the signed
# release, so they are read from it rather than recomputed here.
echo "==> fetching release artefacts for v${version}"
gh release download "v${version}" --repo "${repo}" \
  --pattern 'corralctl_Linux_x86_64.tar.gz' \
  --pattern 'corralctl_Linux_arm64.tar.gz' \
  --dir "${workdir}"

sha_amd64="$(sha256sum "${workdir}/corralctl_Linux_x86_64.tar.gz" | cut -d' ' -f1)"
sha_arm64="$(sha256sum "${workdir}/corralctl_Linux_arm64.tar.gz" | cut -d' ' -f1)"

echo "==> writing PKGBUILD"
cat > "${workdir}/PKGBUILD" <<PKGBUILD
# Maintainer: Sebastien Rousseau <sebastian.rousseau@gmail.com>
# This file is generated by scripts/publish_aur.sh. Do not edit by hand.
pkgname=${pkg}
pkgver=${version}
pkgrel=1
pkgdesc="Clone and organise repositories from GitHub, GitLab, Gitea, Forgejo, Codeberg and Bitbucket, and serve them to AI agents over MCP"
arch=('x86_64' 'aarch64')
url="https://github.com/sebastienrousseau/corralctl"
license=('GPL-3.0-only')
depends=('git')
provides=('corralctl')
conflicts=('corralctl')
source_x86_64=("\${pkgname}-\${pkgver}-x86_64.tar.gz::https://github.com/${repo}/releases/download/v\${pkgver}/corralctl_Linux_x86_64.tar.gz")
source_aarch64=("\${pkgname}-\${pkgver}-aarch64.tar.gz::https://github.com/${repo}/releases/download/v\${pkgver}/corralctl_Linux_arm64.tar.gz")
sha256sums_x86_64=('${sha_amd64}')
sha256sums_aarch64=('${sha_arm64}')

package() {
  install -Dm755 "\${srcdir}/corralctl" "\${pkgdir}/usr/bin/corralctl"
  install -Dm644 "\${srcdir}/LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
PKGBUILD

# .SRCINFO must agree with the PKGBUILD; the AUR rejects a push where it
# does not. Written by hand rather than by makepkg, which is not present
# on a GitHub runner.
echo "==> writing .SRCINFO"
{
  echo "pkgbase = ${pkg}"
  echo "	pkgdesc = Clone and organise repositories from GitHub, GitLab, Gitea, Forgejo, Codeberg and Bitbucket, and serve them to AI agents over MCP"
  echo "	pkgver = ${version}"
  echo "	pkgrel = 1"
  echo "	url = https://github.com/sebastienrousseau/corralctl"
  echo "	arch = x86_64"
  echo "	arch = aarch64"
  echo "	license = GPL-3.0-only"
  echo "	depends = git"
  echo "	provides = corralctl"
  echo "	conflicts = corralctl"
  echo "	source_x86_64 = ${pkg}-${version}-x86_64.tar.gz::https://github.com/${repo}/releases/download/v${version}/corralctl_Linux_x86_64.tar.gz"
  echo "	sha256sums_x86_64 = ${sha_amd64}"
  echo "	source_aarch64 = ${pkg}-${version}-aarch64.tar.gz::https://github.com/${repo}/releases/download/v${version}/corralctl_Linux_arm64.tar.gz"
  echo "	sha256sums_aarch64 = ${sha_arm64}"
  echo ""
  echo "pkgname = ${pkg}"
} > "${workdir}/.SRCINFO"

if [[ "${CORRAL_AUR_DRY_RUN:-}" == "1" ]]; then
  echo "==> dry run: not pushing"
  echo "--- PKGBUILD ---"; cat "${workdir}/PKGBUILD"
  echo "--- .SRCINFO ---"; cat "${workdir}/.SRCINFO"
  exit 0
fi

echo "==> pushing to the AUR"
mkdir -p ~/.ssh
printf '%s\n' "${AUR_KEY:?AUR_KEY is required}" > ~/.ssh/aur
chmod 600 ~/.ssh/aur
ssh-keyscan -H aur.archlinux.org >> ~/.ssh/known_hosts 2>/dev/null
export GIT_SSH_COMMAND="ssh -i ${HOME}/.ssh/aur -o IdentitiesOnly=yes"

git clone "ssh://aur@aur.archlinux.org/${pkg}.git" "${workdir}/aur"
cp "${workdir}/PKGBUILD" "${workdir}/.SRCINFO" "${workdir}/aur/"
cd "${workdir}/aur"
git -c user.name="Sebastien Rousseau" -c user.email="sebastian.rousseau@gmail.com" \
  commit -am "corralctl-bin ${version}" || { echo "nothing to publish"; exit 0; }
git push
echo "==> published ${pkg} ${version}"
